[build-system]
requires = ["setuptools==80.9.0", "wheel==0.45.1"]
build-backend = "setuptools.build_meta"

[project]
name = "tyriavault-backend"
version = "0.1.1"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.121.1",
    "uvicorn[standard]==0.38.0",
    "pydantic==2.12.4",
    "fastapi-cache2==0.2.2",
    "pydantic-settings==2.11.0",
    "sqlalchemy[asyncio]==2.0.44",
    "APScheduler==3.11.1",
    "asyncpg==0.30.0",
    "alembic==1.17.1",
    "python-dotenv==1.2.1",
    "httpx==0.28.1",
    "orjson==3.11.4",
    "pytest-mock==3.15.1",
    "pytest==8.4.2",
    "pytest-asyncio==1.2.0",
    "coverage==7.11.3"
]

authors = [
    { name = "Jade Arkadian" }
]

description = "TyriaVault Backend ⚔️"
readme = "README.md"
license = { text = "MIT" }
keywords = ["gw2", "tyria", "vault", "backend", "api"]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Framework :: FastAPI"
]

[project.optional-dependencies]
uvloop = [
    "uvloop==0.22.1; sys_platform != 'win32'"
]