name: CI/CD Pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build_and_analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: 🧭 Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: 🛠️ Install build tools
        run: pip install --upgrade pip build

      - name: ⬇️ Install project dependencies
        run: pip install .

      - name: 🧾 Run unit tests with coverage
        env:
          ENV: test
        run: |
          coverage run -m pytest app/tests/unit
          coverage xml -o .coverage-reports/coverage-backend.xml
          coverage html -d .coverage-reports/

      - name: 🐳 Run integration tests
        env:
          ENV: test
        run: |
          chmod +x run_integration_tests.sh
          ./run_integration_tests.sh

      - name: 📂 Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: py-coverage-data
          path: .coverage-reports/

      - name: 🏗️ Build package
        run: |
          python -m build

      - name: 🔎 SonarQube Scan
        id: sonarqube-scan
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 #v6
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          ENV: test

      - name: 📊 SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b #v1.2.0
        timeout-minutes: 5
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 📤 Upload build artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: build-artifacts
          path: dist/

  deploy:
    needs: build_and_analyze
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: 📥 Download build artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 #V5
        with:
          name: build-artifacts

      - name: 📰 Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
