name: CI/CD Pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build_and_analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: 🧭 Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: 🛠️ Install build tools
        run: pip install --upgrade pip build

      - name: ⬇️ Install project dependencies
        run: pip install .

      - name: 🧾 Run tests with coverage
        env:
          ENV: test
        run: |
          coverage run -m pytest
          coverage xml -o .coverage-reports/coverage-backend.xml
          coverage html -d .coverage-reports/

      - name: 📂 Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: py-coverage-data
          path: .coverage-reports/

      - name: 🔎 SonarQube Scan
        id: sonarqube-scan
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 #v6
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          ENV: test

      - name: 📊 SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b #v1.2.0
        timeout-minutes: 5
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 💬 Comment PR with SonarQube results
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #v8
        with:
          script: |
            const fs = require('fs');
            const sonarReportPath = '.scannerwork/report-task.txt';

            let sonarUrl = '';
            let qualityGateStatus = '${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}';
            let statusEmoji = '❌';

            if (qualityGateStatus === 'PASSED') {
              statusEmoji = '✔️';
            } else if (qualityGateStatus === 'WARN') {
             qualityGateStatus = 'WARNING'
              statusEmoji = '⚠️';
            }

            try {
              if (fs.existsSync(sonarReportPath)) {
                const reportContent = fs.readFileSync(sonarReportPath, 'utf8');
                const dashboardUrlMatch = reportContent.match(/dashboardUrl=(.*)/);
                if (dashboardUrlMatch) {
                  sonarUrl = dashboardUrlMatch[1];
                }
              } else {
                console.log('SonarQube report not found.');
              }
            } catch (error) {
              console.log('Could not read SonarQube report:', error);
            }

            const comment = `## 🔍 SonarQube Analysis

            ${sonarUrl ? `📊 [View full report on SonarQube](${sonarUrl})` : '⚠️ Could not retrieve report URL'}

            **Quality Gate Status:** ${qualityGateStatus} ${statusEmoji}

            ---
            *This message was automatically generated by the CI/CD Pipeline*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: 📤 Upload build artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: build-artifacts
          path: dist/

  deploy:
    needs: build_and_analyze
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: 📥 Download build artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 #V5
        with:
          name: build-artifacts

      - name: 📰 Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
