name: CI

on:
  push:
    branches: [ "develop", "master" ]   # se ejecuta al hacer push a main
  pull_request:
    branches: [ "develop", "master" ]   # también en PR hacia main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest